# ansible-playbook provision_dynamic.yml --vault-password-file .vault_pass
---
- name: Nginx Webservers Provision
  hosts: webserver-*
  user: tfuser
  become: true
  vars_files:
    - ./roles/webserver/vars/secret.yml
  roles:
    - webserver
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_error_log: "/var/log/nginx/error.log warn"
      nginx_access_log: "/var/log/nginx/access.log"
      nginx_log_format: |-
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"'
      nginx_vhost_template: "vhost.j2"
      nginx_vhosts:
        - listen: "80 default_server"
          server_name: "example.com"
          template: "{{ nginx_vhost_template }}"
          root: "/var/www/example.com"
          index: "index.html"
          extra_parameters: |
            location = /favicon.ico {
                log_not_found off;
            }

- name: Load Balancer Provision
  hosts: load-balancer
  user: tfuser
  become: true        
  roles:
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_error_log: "/var/log/nginx/error.log warn"
      nginx_access_log: "/var/log/nginx/access.log"
      nginx_log_format: |-
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"'
      nginx_vhost_template: "vhost_lb.j2"
      nginx_vhosts:
        - listen: "80 default_server"
          server_name: "balancer.com"
          template: "{{ nginx_vhost_template }}"
          extra_parameters: |
            location / {
                proxy_pass http://webapp;
                proxy_redirect          off;
                proxy_next_upstream     error timeout invalid_header http_500;
                proxy_connect_timeout   2;
                proxy_set_header        Host            $host;
                proxy_set_header        X-Real-IP       $remote_addr;
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            location = /favicon.ico {
                log_not_found off;
            }
# Put Private webservers' IP for upstream using GCE tag.
# Clean up from Undefined junk is used - helpful when one webserver is shutdown.
      nginx_upstreams:
        - name: webapp
          servers: "{{ groups['gce_tag=webserver'] | map('extract',hostvars, ['ansible_default_ipv4','address']) | select('defined') | list }}"
