# ansible-playbook provision_inline.yml --vault-password-file .vault_pass
---
- name: Nginx Webserver Provision
  hosts: all
  become: true
  vars_files:
    - ./roles/webserver/vars/secret.yml
  roles:
    - webserver
    - role: geerlingguy.nginx
      nginx_remove_default_vhost: true
      nginx_error_log: "/var/log/nginx/error.log warn"
      nginx_access_log: "/var/log/nginx/access.log main buffer=16k"
      nginx_log_format: |-
        '$remote_addr - $remote_user [$time_local] "$request" '
        '$status $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"'
      nginx_vhost_template: "vhost.j2"
      nginx_vhosts:
        - listen: "80 default_server"
          server_name: "example.com"
          root: "/var/www/example.com"
          index: "index.html"
          extra_parameters: |
            location = /favicon.ico {
                log_not_found off;
            }